create table
  public.lives (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    date date not null,
    diamonds bigint not null default '0'::bigint,
    duration bigint not null default '0'::bigint,
    username character varying null,
    "userId" uuid null,
    constraint lives_pkey primary key (id),
    constraint lives_id_key unique (id),
    constraint lives_userId_fkey foreign key ("userId") references auth.users (id) on update cascade on delete cascade
  ) tablespace pg_default;